---
- hosts: [lab]
  gather_facts: no
  connection: ansible.netcommon.network_cli
  serial: 25
  vars:
    ansible_network_cli_ssh_type: paramiko
    ansible_command_timeout: 60

  tasks:

  - name: IOS CONFIG - Provision base AAA and L3 configuration
    cisco.ios.ios_config:
      backup: no
      src: "{{ provision_file }}"
